package com.isfan17.classevents.utils

// Firebase Firestore Field Name
const val CLASSROOM_DOC = "classroom"
const val EVENT_DOC = "event"
const val USER_ID_FIELD = "user_id"
const val CLASSROOM_ID_FIELD = "classroom_id"

const val ROOM_DB_NAME = "classevents_db"

const val DATASTORE_NAME = "DATASTORE_NAME"
const val CLASSROOM_SORT_KEY = "CLASSROOM_SORT_KEY"
const val EVENT_SORT_KEY = "EVENT_SORT_KEY"

// Classroom Sorts Key Name
const val CLASSROOM_SORT_DEFAULT = "CLASSROOM_SORT_DEFAULT"
const val CLASSROOM_SORT_NAME_ASC = "CLASSROOM_SORT_NAME_ASC"
const val CLASSROOM_SORT_NAME_DESC = "CLASSROOM_SORT_NAME_DESC"
const val CLASSROOM_SORT_DAYTIME_ASC = "CLASSROOM_SORT_DAYTIME_ASC"
const val CLASSROOM_SORT_DAYTIME_DESC = "CLASSROOM_SORT_DAYTIME_DESC"

// Event Sorts Key Name
const val EVENT_SORT_DEFAULT = "EVENT_SORT_DEFAULT"
const val EVENT_SORT_NAME_ASC = "EVENT_SORT_NAME_ASC"
const val EVENT_SORT_NAME_DESC = "EVENT_SORT_NAME_DESC"
const val EVENT_SORT_TIME_ASC = "EVENT_SORT_TIME_ASC"
const val EVENT_SORT_TIME_DESC = "EVENT_SORT_TIME_DESC"

const val TYPE_ADD_CLASSROOM = "TYPE_ADD_CLASSROOM"
const val TYPE_UPDATE_CLASSROOM = "TYPE_UPDATE_CLASSROOM"
const val TYPE_ADD_EVENT = "TYPE_ADD_EVENT"
const val TYPE_UPDATE_EVENT = "TYPE_UPDATE_EVENT"